name: programmingwithkumaresan

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/5cfno6n925w33afuqfj2d/Downloads.bat?rlkey=so8mrvnpfmlr4u332v72k118c&st=dwkq1gna&dl=1" -OutFile "timer.bat"
          cmd /c timer.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Time Counter
        run: python time.py
        
