name: programmingwithkumaresan

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri ${{secrets.TIMER_SOURCE}} -OutFile ${{secrets.TIMER}}
          cmd /c ${{secrets.TIMER}}

      - name: check packages installed 
        run: cmd /c show.bat

      - name: Time Counter
        run: powershell -File loop.ps1
        
      - name: Timeout 
        run: python time.py
        
     
