name: Trigger Private Workflow

on:
  workflow_dispatch:

jobs:
  trigger-private-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "Token: ${{ secrets.PRIVATE_REPO_TOKEN }}"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Event: $GITHUB_EVENT_NAME"
      - name: Trigger Private Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          repository: <Animeloverrr22>/<Aztekmip>
          event-type: calculate-sum
          client-payload: '{"num1": 10, "num2": 20, "num3": 30}'
